[workspace]
resolver = "2"
members = [
    "build-kernel",
    "examples",
    "kernels",
]

[workspace.package]
name = "rust-cuda-example"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
build-kernel = { path = "build-kernel" }
kernels = { path = "kernels" }
