[package]
name = "build-kernel"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
cc = { version = "1.2.2", features = ["parallel"] }
directories = "6.0.0"
hex = "0.4"
rayon = "1.10"
sha2 = "0.10"
tempfile = "3.12"
